name: Whisper API

on:
  workflow_dispatch: {}   # 手動或 POST 觸發
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run API server
        run: uvicorn app:app --host 0.0.0.0 --port 8000
